server:
  port: 8080
  servlet:
    context-path: /shuttle
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/Shuttle"
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  # Config cloudinary
#  cloudinary:
#    cloud-name: dhlZ71tuc
#    api-key: 851437967967752
#    api-secret: oIRdNHbIZ3NH2LN1ybGZoGmVTAA